### ISSUE TITLE
[bug]启动时报错RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Tigrex-Dai** [FrostN0v0/nonebot-plugin-color-see-see#4]
日志如下：
`
10-07 09:08:35 [ERROR] nonebot | Failed to import "nonebot_plugin_color_see_see"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "D:\systemprogram\Anaconda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot_plugin_color_see_see\__init__.py", line 71, in <module>
    @color_game.handle()
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot_plugin_alconna\matcher.py", line 389, in _decorator
    cls.append_handler(func, parameterless=parameterless)
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot_plugin_alconna\matcher.py", line 360, in append_handler
    handler_ = Dependent[Any].parse(
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 157, in parse
    params = cls.parse_params(call, allow_types)
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 126, in parse_params
    ModelField.construct(
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\compat.py", line 319, in construct
    return cls._construct(name, annotation, field_info or FieldInfo())
  File "D:\Working Place\llbot\Zephrex\.venv\Lib\site-packages\nonebot\compat.py", line 293, in _construct
    return cls(
  File "pydantic\fields.py", line 434, in pydantic.fields.ModelField.__init__
    self.prepare()
  File "pydantic\fields.py", line 555, in pydantic.fields.ModelField.prepare
    self.populate_validators()
  File "pydantic\fields.py", line 829, in pydantic.fields.ModelField.populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "pydantic\validators.py", line 725, in find_validators
    yield from make_dataclass_validator(type_, config)
  File "pydantic\dataclasses.py", line 500, in make_dataclass_validator
    yield from _get_validators(dataclass(dc_cls, config=config, use_proxy=True))
  File "pydantic\dataclasses.py", line 238, in pydantic.dataclasses.dataclass
    return wrap(_cls)
  File "pydantic\dataclasses.py", line 231, in pydantic.dataclasses.dataclass.wrap
    _add_pydantic_validation_attributes(cls, the_config, should_validate_on_init, dc_cls_doc)
  File "pydantic\dataclasses.py", line 354, in pydantic.dataclasses._add_pydantic_validation_attributes
    setattr(dc_cls, '__pydantic_model__', create_pydantic_model_from_dataclass(dc_cls, config, dc_cls_doc))
  File "pydantic\dataclasses.py", line 407, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    model: Type['BaseModel'] = create_model(
  File "pydantic\main.py", line 1024, in pydantic.main.create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
    fields[ann_name] = ModelField.infer(
  File "pydantic\fields.py", line 504, in pydantic.fields.ModelField.infer
    return cls(
  File "pydantic\fields.py", line 434, in pydantic.fields.ModelField.__init__
    self.prepare()
  File "pydantic\fields.py", line 555, in pydantic.fields.ModelField.prepare
    self.populate_validators()
  File "pydantic\fields.py", line 829, in pydantic.fields.ModelField.populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "pydantic\validators.py", line 725, in find_validators
    yield from make_dataclass_validator(type_, config)
  File "pydantic\dataclasses.py", line 500, in make_dataclass_validator
    yield from _get_validators(dataclass(dc_cls, config=config, use_proxy=True))
  File "pydantic\dataclasses.py", line 238, in pydantic.dataclasses.dataclass
    return wrap(_cls)
  File "pydantic\dataclasses.py", line 231, in pydantic.dataclasses.dataclass.wrap
    _add_pydantic_validation_attributes(cls, the_config, should_validate_on_init, dc_cls_doc)
  File "pydantic\dataclasses.py", line 354, in pydantic.dataclasses._add_pydantic_validation_attributes
    setattr(dc_cls, '__pydantic_model__', create_pydantic_model_from_dataclass(dc_cls, config, dc_cls_doc))
  File "pydantic\dataclasses.py", line 407, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    model: Type['BaseModel'] = create_model(
  File "pydantic\main.py", line 1024, in pydantic.main.create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
    fields[ann_name] = ModelField.infer(
  File "pydantic\fields.py", line 504, in pydantic.fields.ModelField.infer
    return cls(
  File "pydantic\fields.py", line 411, in pydantic.fields.ModelField.__init__
    self.type_: Any = convert_generics(type_)
  File "pydantic\typing.py", line 207, in pydantic.typing.convert_generics
    origin = get_origin(tp)
  File "pydantic\typing.py", line 120, in pydantic.typing.get_origin
    return _typing_get_origin(tp) or getattr(tp, '__origin__', None)
  File "D:\systemprogram\Anaconda\Lib\typing.py", line 2444, in get_origin
    if isinstance(tp, (_BaseGenericAlias, GenericAlias,
RecursionError: maximum recursion depth exceeded in __instancecheck__
`

**Comment by Tigrex-Dai** [comment]
我删了好多重复的报错，重复的应该是这一块：

File "pydantic\fields.py", line 434, in pydantic.fields.ModelField.init
self.prepare()
File "pydantic\fields.py", line 555, in pydantic.fields.ModelField.prepare
self.populate_validators()
File "pydantic\fields.py", line 829, in pydantic.fields.ModelField.populate_validators
*(get_validators() if get_validators else list(find_validators(self.type, self.model_config))),
File "pydantic\validators.py", line 725, in find_validators
yield from make_dataclass_validator(type, config)
File "pydantic\dataclasses.py", line 500, in make_dataclass_validator
yield from _get_validators(dataclass(dc_cls, config=config, use_proxy=True))
File "pydantic\dataclasses.py", line 238, in pydantic.dataclasses.dataclass
return wrap(_cls)
File "pydantic\dataclasses.py", line 231, in pydantic.dataclasses.dataclass.wrap
_add_pydantic_validation_attributes(cls, the_config, should_validate_on_init, dc_cls_doc)
File "pydantic\dataclasses.py", line 354, in pydantic.dataclasses._add_pydantic_validation_attributes
setattr(dc_cls, 'pydantic_model', create_pydantic_model_from_dataclass(dc_cls, config, dc_cls_doc))
File "pydantic\dataclasses.py", line 407, in pydantic.dataclasses.create_pydantic_model_from_dataclass
model: Type['BaseModel'] = create_model(
File "pydantic\main.py", line 1024, in pydantic.main.create_model
return meta(model_name, resolved_bases, namespace, **kwds)
File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.new
fields[ann_name] = ModelField.infer(
File "pydantic\fields.py", line 504, in pydantic.fields.ModelField.infer
return cls(

**Comment by FrostN0v0** [comment]
不太清楚原因，方便提供下Py版本、NoneBot2版本和pydantic版本吗？

**Comment by Tosd0** [comment]
> 不太清楚原因，方便提供下Py版本、NoneBot2版本和pydantic版本吗？

我这边也遇到了同样的问题，相关版本如下：

```
(.venv) C:\Users\Administrator\Desktop\bot\gzbot3>pip show nonebot2
Name: nonebot2
Version: 2.3.3
Summary: An asynchronous python bot framework.
Home-page: https://nonebot.dev/
Author: yanyongyu
Author-email: yyy@nonebot.dev
License: MIT
Location: C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages
Requires: loguru, pydantic, pygtrie, python-dotenv, typing-extensions, yarl
Required-by: nonebot-adapter-onebot, nonebot-plugin-alconna, nonebot-plugin-analysis-bilibili, nonebot-plugin-apscheduler, nonebot-plugin-capoo, nonebot-plugin-cesaa, nonebot-plugin-color-see-see, nonebot-plugin-datastore, nonebot-plugin-htmlrender, nonebot-plugin-localstore, nonebot-plugin-longtu, nonebot-plugin-orm, nonebot-plugin-osu-match-monitor, nonebot-plugin-send-anything-anywhere, nonebot-plugin-steam-info, nonebot-plugin-sticker-saver, nonebot-plugin-tortoise-orm, nonebot-plugin-uninfo, nonebot-plugin-waiter, nonebot-plugin-wordcloud, nonebot_plugin_chatrecorder, nonebot_plugin_handle, nonebot_plugin_session, nonebot_plugin_session_orm, nonebot_plugin_userinfo, nonebot_plugin_wordle

(.venv) C:\Users\Administrator\Desktop\bot\gzbot3>pip show pydantic
Name: pydantic
Version: 1.10.18
Summary: Data validation and settings management using python type hints
Home-page: https://github.com/pydantic/pydantic
Author: Samuel Colvin
Author-email: s@muelcolvin.com
License: MIT
Location: C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages
Requires: typing-extensions
Required-by: amis-python, fastapi, nonebot-adapter-onebot, nonebot-plugin-apscheduler, nonebot-plugin-localstore, nonebot-plugin-send-anything-anywhere, nonebot2

(.venv) C:\Users\Administrator\Desktop\bot\gzbot3>python --version
Python 3.11.9
```

**Comment by FrostN0v0** [comment]
升级下 nonebot-plugin-uninfo依赖版本试试
`pdm update nonebot-plugin-uninfo`
或
`pip install --upgrade nonebot-plugin-uninfo`

**Comment by Tosd0** [comment]
> 升级下 nonebot-plugin-uninfo依赖版本试试 `pdm update nonebot-plugin-uninfo` 或 `pip install --upgrade nonebot-plugin-uninfo`

将其从 0.3.0 版本升级到 0.4.1 版本后问题解决了ψ(｀∇´)ψ
谢谢！

**Comment by Tigrex-Dai** [comment]
嘶...我把pydantic和uninfo依赖都升级了还是没有欸，还是相同的报错

**Comment by Tigrex-Dai** [comment]
我的python版本是3.11.7

**Comment by FrostN0v0** [comment]
> 嘶...我把pydantic和uninfo依赖都升级了还是没有欸，还是相同的报错

把本插件版本也升级到最新试试呢？

**Comment by Tigrex-Dai** [comment]
ah，好了，对不起，我的问题、 感激不尽！
